# default config
server:
  port: 18080
  name: 抢红包系统

db:
  driverName: mysql
  host: 127.0.0.1:3306
  database: envelope
  user: root
  password: 123456
  # 连接池配置
  connMaxLifetime: 12h
  maxIdleConns: 1
  maxOpenConns: 3
  loggingEnabled: false
  # 数据源参数配置
  options:
    charset: utf8
    parseTime: true
    loc: Local
