# 开发环境
system:
  host: 0.0.0.0
  port: 9000
  name: 抢红包系统
  account:
    userId: 1
    userName: 系统红包账户
    accountNo: system_red_envelope_account

jwt:
  # 秘钥
  salt: 123456
  # 存储在 request header 中的 key
  key: X-Token
  # 有效期 7 天
  period: 604800

db:
  driverName: mysql
  port: 3306
  host: 127.0.0.1
  database: red
  user: root
  password: 123456
  # 连接池配置
  connMaxLifetime: 12h
  maxIdleConns: 1
  maxOpenConns: 3
  loggingEnabled: false
  # 数据源参数配置
  options:
    charset: utf8
    parseTime: true
    loc: Local

log:
  dir: ./tmp/log/
  name: red.log
  level: debug
  enableLineLog: true
  localTime: true
